### ISSUE TITLE
Falta Estado de México

### ISSUE THREAD

**Issue by paucuaram** [Munett/API-Codigos-Postales#1]
En tu tabla cheque el cp 57000 que pertenece al estado de mexico y me mando a Guanajuato.
Busqué el Estado de México y no lo tienes en la lista.

**Comment by acrogenesis** [comment]
@paucuaram busque el código postal `57000` y si me sale en el estado de mexico.

```
[  
   {  
      "codigo_postal":"57000",
      "colonia":"Benito Juárez (La Aurora)",
      "municipio":"Nezahualcóyotl",
      "estado":"México"
   }
]
```

**Comment by acrogenesis** [comment]
@paucuaram voy a cerrar el Issue, si sigues teniendo problemas dime.
