### ISSUE TITLE
¿Murió este grandioso API? - No such app (404)

### ISSUE THREAD

**Issue by IvyBridge2017** [Munett/API-Codigos-Postales#10]
Hola, desde hace unos dias ya no funciona el API, al intentar cargar la página muestra este mensaje

![image](https://user-images.githubusercontent.com/34945468/35186694-ed51f592-fddd-11e7-91b6-ec9dcc78765f.png)

Y en la consola (JS) cuando hace el request por AJAX muestra esto:

![image](https://user-images.githubusercontent.com/34945468/35186697-040c7b2c-fdde-11e7-81b9-929ddf931fc7.png)

**Comment by acrogenesis** [comment]
Por demanda popular lo volvi a subir. Estarías dispuesto y cuanto a pagar por este API quizá con un modelo de X número de llamadas gratis al mes?

**Comment by IvyBridge2017** [comment]
Hmm no entendí bien tu respuesta. Me estás ofreciendo el API? o a que te refieres? Una disculpa

**Comment by acrogenesis** [comment]
Tener al API vivo me cuesta dinero, como usuario del API estarías dispuesto a pagar algún monto mensual por usarlo?

**Comment by acrogenesis** [comment]
Ahorita el api ya lo volví a subir y esta funcionando

**Comment by IvyBridge2017** [comment]
Hmm, correcto... Pues, eso depende, no sé de cuanto estemos hablando, sin embargo, que no el API es el de éste GIT? supongo que lo puedo hacer funcionar sin que tenga que estar pagando por hosting o me equivoco?

**Comment by cesasol** [comment]
Te apoyo en la idea de monetizar tu api, pero teniendo la opción de autohostear la api yo creo que sería viable para ti cobrar por llamadas por mes por dominio excluyendo entornos de prueba, así permites a los desarrolladores probar tu api antes de lanzar una aplicación que la use

**Comment by acrogenesis** [comment]
Por ambientes de prueba @cesasol te refieres a localhost, lvh.me, 127.0.0.1 etc?

**Comment by cesasol** [comment]
Esos sería más de desarrollo en mi opinión, me refería a cualquier aplicación que no tenga pensado ser usado por el usuario final, si no donde los desarrolladores pueden probar la aplicación. Por ejemplo que el sitio web no indexe o que la aplicación no esté publicada en tiendas

**Comment by sanPuerquitoProgramador** [comment]
Estoy de acuerdo con Acrogenesis, el proyecto es público y lo puedes descargar e instalar en tu propio server o desarrollo, pero tenerlo en heroku de manera pública para que todos lo puedan usar cuesta dinero. Yo pagaría el servicio por X llamadas mensuales y trasladaría ese costo a mi cliente. Gracias por el desarrollo Acrogenesis. El día que pienses en ponerlo de pago yo lo contrato.
