### ISSUE TITLE
API No Funcionando

### ISSUE THREAD

**Issue by deviaan** [Munett/API-Codigos-Postales#11]
Hola,

Parece que el API no esta respondiendo. Sigue viva o lo van a transicionar a un modelo de paga?

Gracias!

**Comment by acrogenesis** [comment]
Hola @deviaan es un problema con el limite de uso gratis en la BD de Heroku ya lo estoy migrando a otro lado para no tener ese problema, en unos 10 minutos queda solucionado. Gracias por reportarlo

**Comment by deviaan** [comment]
Oh ok!

Muchas gracias!
