### ISSUE TITLE
Application error

### ISSUE THREAD

**Issue by Misaelarios2** [Munett/API-Codigos-Postales#14]
Se produjo un error en la aplicacion y esta no contesta las peticiones.
Error 503 (Servicio no disponible).

**Comment by GioGuemez** [comment]
A mi me pasó igual.

Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail

**Comment by Kikemonk** [comment]
A mi me acaba de pasar y estaba funcionando bien
