### ISSUE TITLE
 Application error

### ISSUE THREAD

**Issue by krathos** [Munett/API-Codigos-Postales#15]
Este error comenzo desde el pasado sabado 24 de Noviembre 2018
Que podra ser?

Gracias!

**Comment by juanhuerta** [comment]
¿Alguna noticia? ¡Gracias!

**Comment by CristianMtz28** [comment]
Creo que es porque la base de datos de correos de México se actualizó el 23 de noviembre y esta API jala los datos de ahí; esperemos no tarde mucho en resolverse el problema, de antemano gracias

**Comment by CristianMtz28** [comment]
Ya sirvió no sé si el dueño movió algo; si lees esto 2 cosas

1.- Muchas gracias
2.- Te mande un correo para poder usar el API sin que falle en ningún momento no sé si te podemos ayudar con algo y quería ver si podía usar el API de manera privada, me gustaría contactarme contigo para llegar a un acuerdo y nuevamente muchas gracias :)
