### ISSUE TITLE
Problema con los CORS

### ISSUE THREAD

**Issue by BitQuarkApps** [Munett/API-Codigos-Postales#18]
Hola, estoy utilizando su API para un proyecto escolar y todo funcionaba perfecto, hasta que un día los CORS comenzaron a bloquearme las peticiones desde localhost, subí mi repositorio a un servidor y también me rechazaban las peticiones.

> Access to XMLHttpRequest at 'https://api-codigos-postales.herokuapp.com/v2/codigo_postal/29077' from origin 'http://127.0.0.1:8000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by MikeG96** [comment]
¿Que cabeceras estás enviando?

**Comment by Nemutagk** [comment]
Tengo el mismo problema, se hace petición vía axios, las cabeceras que se envían son:

- Host: api-codigos-postales.herokuapp.com
- User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0
- Accept: */*
- Accept-Language: en-US,en;q=0.5
- Accept-Encoding: gzip, deflate, br
- Access-Control-Request-Method: GET
- Referer: https://site.dev/
- Origin: https://site.dev
- DNT: 1
- Connection: keep-alive

**Comment by IDSFernando** [comment]
En mi caso, utilicé fetch (JavaScript) y logré acceder a la API
