### ISSUE TITLE
Error al buscar código postal

### ISSUE THREAD

**Issue by oskyGomez** [Munett/API-Codigos-Postales#19]
al consumir el webservice:
https://api-codigos-postales.herokuapp.com/v2/codigo_postal/66240

arroja lo siguiente:
An unhandled lowlevel error occurred. The application logs may have details.

esto con cualquier código postal.

**Comment by acrogenesis** [comment]
Fue un problema anoche, ahorita ya esta todo bien

**Comment by oskyGomez** [comment]
Estuve haciendo pruebas y sigue saliendo el mismo error con diferentes códigos postales:
66236
64930
66235
