### ISSUE TITLE
heroku application error

### ISSUE THREAD

**Issue by oskyGomez** [Munett/API-Codigos-Postales#21]
la aplicación está abajo

**Comment by Dreicored-19** [comment]
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail.
The service its down

**Comment by acrogenesis** [comment]
Si a veces sucede, ahorita esta hosteado en un servidor gratis de heroku y si se le acaban las horas se suspende el servicio.
