### ISSUE TITLE
Obtener Ciudad del código postal consultado

### ISSUE THREAD

**Issue by adelgadox** [Munett/API-Codigos-Postales#5]
Hola! Excelente tu código, te agradezco mucho la publicación. Me gustaría saber si hay manera de obtener también la Ciudad en el json que el servicio devuelve ya que no lo trae sin embargo de la página de códigos postales si retornar este valor (http://www.correosdemexico.gob.mx/ServiciosLinea/Paginas/ccpostales.aspx). Se requiere llamar a otro servicio o configurar algo de mi lado?

Saludos

**Comment by acrogenesis** [comment]
Hola @adelgadox perdón por contestarte tan tarde sería de modificar un poco este archivo https://github.com/Munett/API-Codigos-Postales/blob/master/Rakefile (y el modelo) para que también guarde esa información
