### ISSUE TITLE
Acceso AJAX

### ISSUE THREAD

**Issue by softnya** [Munett/API-Codigos-Postales#6]
Hola amigo, excelente codigo, solo un detalle, estoy tratando de obtener el JSON por AJAX de jQuery pero me da un error de "Access-Control-Allow-Origin", esta pensado para accesarlo por otro metodo? O es necesario otorgar el permiso previo, el dominio de donde requiero ingresar es sivepro.com, saludos

**Comment by erm3nda** [comment]
Lo que tienes que hacer es aceptar la url del API en tu servidor, seteandolo en los headers, así al ser consultada la página los headers de tu página indican que otros servicios pueden ser consultados. Otra opcion, es que tengas un mini servicio web en el mismo dominio y que vía get/post sirvas el resultado, que es la manera más fácil y socorrida de saltarse todo tipo de seguridad referente a Allow-Origin.
